name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.4', '8.5']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
      - run: composer install --no-interaction --no-progress
      - run: composer cs
      - run: composer stan
      - run: composer test
      - run: XDEBUG_MODE=coverage composer infection
